# Generated by Django 4.0.4 on 2023-04-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lev_cir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(max_length=3)),
                ('especialidad', models.CharField(max_length=100)),
                ('asa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='lev_cir.conmorbilidad')),
            ],
        ),
    ]
