# Generated by Django 4.0.4 on 2023-04-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lev_cir', '0002_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='lev_cir.tipo'),
        ),
    ]
